## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [4]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    'Age', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'NumCompaniesWorked',
    'PercentSalaryHike', 'TotalWorkingYears', 'WorkLifeBalance'
]

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
X_df.dtypes

Age                        int64
DistanceFromHome           int64
Education                  int64
EnvironmentSatisfaction    int64
JobInvolvement             int64
JobLevel                   int64
JobSatisfaction            int64
NumCompaniesWorked         int64
PercentSalaryHike          int64
TotalWorkingYears          int64
WorkLifeBalance            int64
dtype: object

In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

In [6]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X_df = X_df.apply(pd.to_numeric, errors='coerce')

In [7]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [10]:
# Create a OneHotEncoder for the Department column
encoder_department = OneHotEncoder(sparse=False)

# Fit the encoder to the training data
encoder_department.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_department = encoder_department.transform(y_train[['Department']])
y_test_department = encoder_department.transform(y_test[['Department']])

NameError: name 'OneHotEncoder' is not defined

In [ ]:
# Create a OneHotEncoder for the Attrition column
encoder_attrition = OneHotEncoder(sparse=False)

# Fit the encoder to the training data
encoder_attrition.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attrition = encoder_attrition.transform(y_train[['Attrition']])
y_test_attrition = encoder_attrition.transform(y_test[['Attrition']])

## Create, Compile, and Train the Model

In [ ]:
# Find the number of columns in the X training data
num_features = X_train.shape[1]

# Create the input layer
inputs = layers.Input(shape=(num_features,))

# Create at least two shared layers
shared_layer_1 = layers.Dense(32, activation='relu')(inputs)
shared_layer_2 = layers.Dense(16, activation='relu')(shared_layer_1)

In [ ]:
# Create a branch for Department # with a hidden layer and an output layer
# Create the hidden layer
department_branch = layers.Dense(8, activation='relu')(shared_layer_2)

# Create the output layer
department_output = layers.Dense(y_train_department.shape[1], activation='softmax', name='department_output')(department_branch)

In [ ]:
# Create a branch for Attrition # with a hidden layer and an output layer
# Create the hidden layer
attrition_branch = layers.Dense(8, activation='relu')(shared_layer_2)

# Create the output layer
attrition_output = layers.Dense(y_train_attrition.shape[1], activation='softmax', name='attrition_output')(attrition_branch)

In [ ]:
# Create the model
model = Model(inputs=inputs, outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Summarize the model
model.summary()

In [ ]:
# Train the model
model.fit(X_train, [y_train_department, y_train_attrition], epochs=100, batch_size=10)

In [ ]:
# Evaluate the model with the testing data
department_loss, department_accuracy = model.evaluate(X_test, y_test_department)
attrition_loss, attrition_accuracy = model.evaluate(X_test, y_test_attrition)

In [ ]:
# Print the accuracy for both department and attrition
print(f'Department Accuracy: {department_accuracy}')
print(f'Attrition Accuracy: {attrition_accuracy}')

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?



```
# This is formatted as code
```

YOUR ANSWERS HERE

1. Accuracy might not be the best metric to use on this data, especially if there is class imbalance between the categories in the Department and Attrition columns. Alternative metrics such as precision, recall, or F1-score could provide additional insights into the model's performance.

2. I used the 'softmax' activation function for both output layers, as it is suitable for multi-class classification tasks. It allows the model to output a probability distribution over the predicted classes for both the Department and Attrition targets.

3. The model could be improved by adjusting the architecture, such as adding more hidden layers or increasing the number of neurons. Additionally, hyperparameter tuning, using different activation functions, and experimenting with different optimizers could enhance performance. Collecting more data or using techniques to handle class imbalance might also be beneficial.